#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : postfix
Version  : 3.4.5
Release  : 1
URL      : http://ftp.porcupine.org/mirrors/postfix-release/official/postfix-3.4.5.tar.gz
Source0  : http://ftp.porcupine.org/mirrors/postfix-release/official/postfix-3.4.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-4-Clause EPL-2.0
Requires: postfix-bin = %{version}-%{release}
Requires: postfix-libexec = %{version}-%{release}
Requires: postfix-license = %{version}-%{release}
Requires: postfix-man = %{version}-%{release}
BuildRequires : openssl-dev

%description
Purpose of this document
========================
This document describes how to add your own SASL implementation to
Postfix.  You don't have to provide both the server and client side.
You can provide just one and omit the other. The examples below
assume you do both.

%package bin
Summary: bin components for the postfix package.
Group: Binaries
Requires: postfix-libexec = %{version}-%{release}
Requires: postfix-license = %{version}-%{release}

%description bin
bin components for the postfix package.


%package libexec
Summary: libexec components for the postfix package.
Group: Default
Requires: postfix-license = %{version}-%{release}

%description libexec
libexec components for the postfix package.


%package license
Summary: license components for the postfix package.
Group: Default

%description license
license components for the postfix package.


%package man
Summary: man components for the postfix package.
Group: Default

%description man
man components for the postfix package.


%prep
%setup -q -n postfix-3.4.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558765962
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags} CCARGS="-DNO_DB -DUSE_TLS `pkg-config --cflags openssl`" AUXLIBS="`pkg-config --libs openssl`"


%install
export SOURCE_DATE_EPOCH=1558765962
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/postfix
cp COPYRIGHT %{buildroot}/usr/share/package-licenses/postfix/COPYRIGHT
make non-interactive-package install_root=%{buildroot} manpage_directory=/usr/share/man
## install_append content
mv %{buildroot}/usr/sbin/sendmail %{buildroot}/usr/sbin/sendmail-postfix
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mailq
/usr/bin/newaliases
/usr/sbin/postalias
/usr/sbin/postcat
/usr/sbin/postconf
/usr/sbin/postdrop
/usr/sbin/postfix
/usr/sbin/postkick
/usr/sbin/postlock
/usr/sbin/postlog
/usr/sbin/postmap
/usr/sbin/postmulti
/usr/sbin/postqueue
/usr/sbin/postsuper
/usr/sbin/sendmail-postfix

%files libexec
%defattr(-,root,root,-)
/usr/libexec/postfix/anvil
/usr/libexec/postfix/bounce
/usr/libexec/postfix/cleanup
/usr/libexec/postfix/discard
/usr/libexec/postfix/dnsblog
/usr/libexec/postfix/error
/usr/libexec/postfix/flush
/usr/libexec/postfix/lmtp
/usr/libexec/postfix/local
/usr/libexec/postfix/master
/usr/libexec/postfix/nqmgr
/usr/libexec/postfix/oqmgr
/usr/libexec/postfix/pickup
/usr/libexec/postfix/pipe
/usr/libexec/postfix/post-install
/usr/libexec/postfix/postfix-script
/usr/libexec/postfix/postfix-tls-script
/usr/libexec/postfix/postfix-wrapper
/usr/libexec/postfix/postlogd
/usr/libexec/postfix/postmulti-script
/usr/libexec/postfix/postscreen
/usr/libexec/postfix/proxymap
/usr/libexec/postfix/qmgr
/usr/libexec/postfix/qmqpd
/usr/libexec/postfix/scache
/usr/libexec/postfix/showq
/usr/libexec/postfix/smtp
/usr/libexec/postfix/smtpd
/usr/libexec/postfix/spawn
/usr/libexec/postfix/tlsmgr
/usr/libexec/postfix/tlsproxy
/usr/libexec/postfix/trivial-rewrite
/usr/libexec/postfix/verify
/usr/libexec/postfix/virtual

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/postfix/COPYRIGHT

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mailq.1
/usr/share/man/man1/newaliases.1
/usr/share/man/man1/postalias.1
/usr/share/man/man1/postcat.1
/usr/share/man/man1/postconf.1
/usr/share/man/man1/postdrop.1
/usr/share/man/man1/postfix-tls.1
/usr/share/man/man1/postfix.1
/usr/share/man/man1/postkick.1
/usr/share/man/man1/postlock.1
/usr/share/man/man1/postlog.1
/usr/share/man/man1/postmap.1
/usr/share/man/man1/postmulti.1
/usr/share/man/man1/postqueue.1
/usr/share/man/man1/postsuper.1
/usr/share/man/man1/sendmail.1
/usr/share/man/man5/access.5
/usr/share/man/man5/aliases.5
/usr/share/man/man5/body_checks.5
/usr/share/man/man5/bounce.5
/usr/share/man/man5/canonical.5
/usr/share/man/man5/cidr_table.5
/usr/share/man/man5/generic.5
/usr/share/man/man5/header_checks.5
/usr/share/man/man5/ldap_table.5
/usr/share/man/man5/lmdb_table.5
/usr/share/man/man5/master.5
/usr/share/man/man5/memcache_table.5
/usr/share/man/man5/mysql_table.5
/usr/share/man/man5/nisplus_table.5
/usr/share/man/man5/pcre_table.5
/usr/share/man/man5/pgsql_table.5
/usr/share/man/man5/postconf.5
/usr/share/man/man5/postfix-wrapper.5
/usr/share/man/man5/regexp_table.5
/usr/share/man/man5/relocated.5
/usr/share/man/man5/socketmap_table.5
/usr/share/man/man5/sqlite_table.5
/usr/share/man/man5/tcp_table.5
/usr/share/man/man5/transport.5
/usr/share/man/man5/virtual.5
/usr/share/man/man8/anvil.8
/usr/share/man/man8/bounce.8
/usr/share/man/man8/cleanup.8
/usr/share/man/man8/defer.8
/usr/share/man/man8/discard.8
/usr/share/man/man8/dnsblog.8
/usr/share/man/man8/error.8
/usr/share/man/man8/flush.8
/usr/share/man/man8/lmtp.8
/usr/share/man/man8/local.8
/usr/share/man/man8/master.8
/usr/share/man/man8/oqmgr.8
/usr/share/man/man8/pickup.8
/usr/share/man/man8/pipe.8
/usr/share/man/man8/postlogd.8
/usr/share/man/man8/postscreen.8
/usr/share/man/man8/proxymap.8
/usr/share/man/man8/qmgr.8
/usr/share/man/man8/qmqpd.8
/usr/share/man/man8/scache.8
/usr/share/man/man8/showq.8
/usr/share/man/man8/smtp.8
/usr/share/man/man8/smtpd.8
/usr/share/man/man8/spawn.8
/usr/share/man/man8/tlsmgr.8
/usr/share/man/man8/tlsproxy.8
/usr/share/man/man8/trace.8
/usr/share/man/man8/trivial-rewrite.8
/usr/share/man/man8/verify.8
/usr/share/man/man8/virtual.8
